### ISSUE TITLE
Password Not Saving In OBS

### ISSUE THREAD

**Issue by dbgamerboy** [obsproject/obs-websocket#838] opened 2021-10-18 23:23 UTC
##### Steps to reproduce and other useful info
I go to OBS > Tools > WebSockets Server Settings > I type the password I want and it just seems like to reset everytime it's so frustrating. I need this to work because I need this for TouchPortal and my stream. 
##### Technical information
- **Operating System** : Windows 10 Pro
- **OBS Studio version** : 27.1.3
- **obs-websocket version** :  4.9.1

**Comment by dbgamerboy** [comment] 2021-10-18 23:23
how do i include a log file

**Comment by dbgamerboy** [comment] 2021-10-18 23:58
if i cant change password what is the default password set? because i cannot connect to OBS

**Comment by dbgamerboy** [comment] 2021-10-19 03:19
pls halp

**Comment by dbgamerboy** [comment] 2021-10-19 03:26
> Settings are stored in your profile configuration. If the password isn't saving, then the only logical possibility is that your profiles directory is not writeable. You can validate this because no other options in the OBS settings will persist across reloads.

what directory is the profiles folder in?

**Comment by dbgamerboy** [comment] 2021-10-19 03:27
Really need to fix this for my stream tonight really hope I can solve this

**Comment by tt2468** [comment] 2021-10-19 05:49
Windows folders always have the read-only checkbox semi-checked due to dumb reasons. The reality is that it's usually lying. Have you tried launching OBS as administrator?

**Comment by dbgamerboy** [comment] 2021-10-19 05:53
I removed the password, enabled auto connect and FINALLY OBS connected with Touch Portal (the reason I made this post)

Hours of frustration.

I will try to run as an admin.

**Comment by tt2468** [comment] 2021-11-21 07:48
Sorry, I'm going to have to close this as unconfirmed, as I have still not been able to reproduce the issue, and 5.0.0 is coming out soon.

**Closed by tt2468** 2021-11-21 07:48 UTC
Labels: Bug: Unconfirmed

**Comment by doriantaylor** [comment] 2022-06-01 12:57
This also happens with OBS 27.2.1 on Ubuntu (which is unfortunately the latest snap from 2022-02-24): you ostensibly can't save a password or disable them outright. It doesn't look like it writes out any configuration state (so I can't even see what the default password is supposed to be and just use that).

**Comment by doriantaylor** [comment] 2022-06-01 13:48
Ah wait, looks like it might be [the client](https://github.com/sachac/obs-websocket-el):
```
09:41:29.744: [obs-websocket] new client connection from 127.0.0.1:48946
09:41:29.744: [obs-websocket] Request >> '{"request-type":"GetAuthRequired","message-id":"100"}'
09:41:29.744: [obs-websocket] Request >> '{"request-type":"GetStreamingStatus","message-id":"101"}'
09:41:29.744: [obs-websocket] Request >> '{"request-type":"GetCurrentScene","message-id":"102"}'
09:41:29.744: [obs-websocket] Response << '{"error":"Not Authenticated","message-id":"101","status":"error"}'
09:41:29.744: [obs-websocket] Response << '{"authRequired":true,"challenge":"j+JGffEjUVnDfyNvq02pAykyj8/kYYRXuVQ6dJMbhdQ=","message-id":"100","salt":"O/sMSaM/hnPrACfB4Y69Ow+cnL0BYhqAPNlYsWOl1y0=","status":"ok"}'
09:41:29.744: [obs-websocket] Response << '{"error":"Not Authenticated","message-id":"102","status":"error"}'
09:41:29.792: [obs-websocket] Request >> '{"request-type":"Authenticate","message-id":"103","auth":"csX1kYzEcuqPuhxx4FI0bOAAyHX2ZBaezp9MIdQ+LPw="}'
09:41:29.792: [obs-websocket] Response << '{"message-id":"103","status":"ok"}'
```
It naïvely sends message 102 and then whines about the (correct) error response to it before getting the response from 103. Sorry to bother.

I wonder if other clients behave this way too, and that's that's causing this line of inquiry?
