### ISSUE TITLE
Feature Request: Open UI Dialogs

### ISSUE THREAD

**Issue by AlcaDesign** [obsproject/obs-websocket#846] opened 2021-11-10 05:42 UTC
##### Issue type

- Feature request

##### Description

- Add request to open the interact dialog
- Add request to open the properties dialog
- Add request to open the filters dialog

**Comment by tt2468** [comment] 2021-11-21 08:07
Duplicate of #672

**Comment by AlcaDesign** [comment] 2021-11-21 08:18
I would like to open the interact menu so that the user can use it, not necessarily to send input to it whether it is open or not. It can be arduous or at least inconvenient to get to the interact menu when it's deep in scenes and you don't want to have to change scenes to get to it. I wouldn't say this was a duplicate request, just related.

**Closed** 2021-12-30 05:08 UTC
Labels: Medium Priority, Issue: Feature Request, Issue: PR Pending
